CREATE TABLE "user"(
    id TEXT NOT NULL UNIQUE PRIMARY KEY
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    birthday TIMESTAMP NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
);
